spring.application.name=jwt-practice
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=123456
spring.datasource.username=postgres
spring.datasource.url= jdbc:postgresql://localhost:5432/spring_jwt
